version: '1.0'

services:
  postgres:
    container_name: auth_postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data    
    networks:
      - auth-nest-course

volumes:
  postgres_data:

networks:
  auth-nest-course:  